#!/usr/bin/env node

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

async function run() {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);
  const projectRoot = resolve(__dirname, '..', '..');

  const dateSlug = new Date().toISOString().split('T')[0];
  const inputFile = join(projectRoot, 'reports', 'seo', `${dateSlug}.json`);
  const outputFile = join(projectRoot, 'reports', 'seo', `${dateSlug}.md`);

  let json;
  try {
    const raw = await readFile(inputFile, 'utf8');
    json = JSON.parse(raw);
  } catch (error) {
    console.error('[seo:report] Unable to read audit JSON. Run npm run seo:audit first.');
    throw error;
  }

  const lines = [
    `# SEO Daily Report ? ${dateSlug}`,
    '',
    `- Generated At: ${json.generatedAt}`,
    `- Total Indexed Pages (approx): ${json.totals?.pageCount ?? 'n/a'}`,
    '',
    '## Sample Pages Reviewed',
    '',
  ];

  const sampleList = Array.isArray(json.samples) && json.samples.length > 0
    ? json.samples
    : ['No sample pages captured.'];

  for (const item of sampleList) {
    lines.push(`- ${item}`);
  }

  lines.push('', '---', '', '_Automated summary generated by npm run seo:all_.');

  await writeFile(outputFile, lines.join('\n'), 'utf8');
  console.log(`[seo:report] Wrote ${outputFile}`);
}

run().catch((error) => {
  console.error('[seo:report] Failed to generate markdown report');
  console.error(error);
  process.exitCode = 1;
});
