const fs = require('fs');
const path = require('path');

// Helper to get all files in a directory recursively
function getFiles(dir, files = []) {
  try {
    const fileList = fs.readdirSync(dir);
    for (const file of fileList) {
      const name = `${dir}/${file}`;
      if (fs.statSync(name).isDirectory()) {
        getFiles(name, files);
      } else {
        files.push(name);
      }
    }
  } catch (e) {
    // ignore
  }
  return files;
}

// 1. Parse public/sitemap.xml (Generated by build)
let sitemapUrls = [];
try {
  const xml = fs.readFileSync('public/sitemap.xml', 'utf8');
  // Simple regex for <loc>...</loc>
  const regex = /<loc>(.*?)<\/loc>/g;
  let match;
  while ((match = regex.exec(xml)) !== null) {
    sitemapUrls.push(match[1]);
  }
} catch (e) {
  console.error("Could not read public/sitemap.xml. Ensure build has run.");
}

// 2. Get Actual MDX content
const mdxFiles = fs.readdirSync('content/blog')
  .filter(f => f.endsWith('.mdx'))
  .map(f => `https://www.drsayuj.info/blog/${f.replace('.mdx', '')}`);

// 3. Get Explicit Page Routes
const pageFiles = getFiles('app');
const pageRoutes = pageFiles
  .filter(f => f.endsWith('/page.tsx') || f.endsWith('/page.js'))
  .map(f => {
    let route = f.replace('app', '').replace('/page.tsx', '').replace('/page.js', '');
    if (route === '') route = '/';
    return `https://www.drsayuj.info${route}`;
  })
  .filter(r => !r.includes('[') && !r.includes('('));

// Combine and Audit
// Normalize to remove trailing slashes for comparison
const normalize = u => u.replace(/\/$/, '');
const sitemapSet = new Set(sitemapUrls.map(normalize));
const allPotentialUrls = new Set([...sitemapUrls, ...mdxFiles, ...pageRoutes]);

console.log('url,type,in_sitemap,in_filesystem,status');

for (const rawUrl of allPotentialUrls) {
  const url = normalize(rawUrl);
  const path = url.replace('https://www.drsayuj.info', '');

  let type = 'other';
  if (path === '' || path === '/') type = 'home';
  else if (path.includes('/blog')) type = 'blog';
  else if (path.includes('/services')) type = 'service';
  else if (path.includes('/conditions')) type = 'condition';
  else if (path.includes('/locations') || path.includes('/neurosurgeon-')) type = 'location';

  const inSitemap = sitemapSet.has(url);

  // Check FS existence (approximate)
  let inFs = false;
  if (type === 'blog') {
      const slug = path.split('/').pop();
      if (fs.existsSync(`content/blog/${slug}.mdx`)) inFs = true;
      else if (fs.existsSync(`app${path}/page.tsx`)) inFs = true;
  } else {
       if (fs.existsSync(`app${path}/page.tsx`) || path === '') inFs = true;
       // Handle redirects/virtual pages if known
       if (path === '/sitemap.xml') inFs = true;
  }

  // Filter out internal/admin pages from being flagged as "Orphan" if they are truly internal
  const isInternal = path.startsWith('/admin') || path.startsWith('/api') || path.startsWith('/auth') || path.includes('test') || path.includes('drafts');

  let status = 'OK';
  if (inSitemap && !inFs) status = 'Ghost (In Sitemap, No File)';
  if (!inSitemap && inFs && !isInternal) status = 'Orphan (In File, No Sitemap)';
  if (!inSitemap && !inFs) status = 'Unknown';

  console.log(`${url},${type},${inSitemap},${inFs},"${status}"`);
}
