#!/usr/bin/env bash

# Citation Directory Update Script
# Updates NAP consistency across major citation directories

echo "🏥 Citation Directory Update Script"
echo "=================================="
echo ""

# Standardized NAP
NAP_NAME="Dr. Sayuj Krishnan S"
NAP_ADDRESS="Yashoda Hospital, Room 317, OPD Block, Malakpet, Hyderabad 500036"
NAP_PHONE="+91 9778280044"
NAP_EMAIL="neurospinehyd@drsayuj.com"
NAP_WEBSITE="https://www.drsayuj.com"

# UTM-tracked appointment links
APPOINTMENT_LINK="https://www.drsayuj.com/appointments?utm_source=citation&utm_medium=directory&utm_campaign=book"
TELECONSULT_LINK="https://www.drsayuj.com/appointments?utm_source=citation&utm_medium=directory&utm_campaign=teleconsult"

echo "📋 Standardized NAP Information:"
echo "Name: $NAP_NAME"
echo "Address: $NAP_ADDRESS"
echo "Phone: $NAP_PHONE"
echo "Email: $NAP_EMAIL"
echo "Website: $NAP_WEBSITE"
echo ""
echo "🔗 UTM-Tracked Links:"
echo "Appointments: $APPOINTMENT_LINK"
echo "Teleconsult: $TELECONSULT_LINK"
echo ""

echo "📝 Citation Directory Update Checklist:"
echo "======================================"
echo ""

echo "1. 🏥 PRACTO"
echo "   URL: https://www.practo.com/hyderabad/doctor/dr-sayuj-krishnan-neurosurgeon"
echo "   Actions:"
echo "   - Update NAP information"
echo "   - Add appointment booking link: $APPOINTMENT_LINK"
echo "   - Update services list"
echo "   - Add teleconsult option: $TELECONSULT_LINK"
echo ""

echo "2. 📞 JUSTDIAL"
echo "   URL: https://www.justdial.com/Hyderabad/Dr-Sayuj-Krishnan-Neurosurgeon"
echo "   Actions:"
echo "   - Verify NAP consistency"
echo "   - Update business hours"
echo "   - Add appointment link: $APPOINTMENT_LINK"
echo "   - Update photos and services"
echo ""

echo "3. 🩺 LYRATE"
echo "   URL: https://www.lybrate.com/hyderabad/doctor/dr-sayuj-krishnan-neurosurgeon"
echo "   Actions:"
echo "   - Update profile information"
echo "   - Add consultation booking: $APPOINTMENT_LINK"
echo "   - Update specializations"
echo "   - Add teleconsult option: $TELECONSULT_LINK"
echo ""

echo "4. 🗺️ BING PLACES"
echo "   URL: https://www.bing.com/maps"
echo "   Actions:"
echo "   - Search for 'Dr. Sayuj Krishnan Yashoda Hospital Malakpet'"
echo "   - Claim/update business listing"
echo "   - Update NAP information"
echo "   - Add website: $NAP_WEBSITE"
echo ""

echo "5. 🍎 APPLE MAPS"
echo "   URL: https://maps.apple.com"
echo "   Actions:"
echo "   - Search for business location"
echo "   - Report issue or suggest edit"
echo "   - Update NAP information"
echo "   - Add website and phone"
echo ""

echo "6. 🏥 YASHODA HOSPITAL DIRECTORY"
echo "   URL: https://www.yashodahospitals.com/doctor/dr-sayuj-krishnan/"
echo "   Actions:"
echo "   - Verify doctor profile is up-to-date"
echo "   - Update consultation timings"
echo "   - Add appointment booking link: $APPOINTMENT_LINK"
echo ""

echo "7. 📱 GOOGLE BUSINESS PROFILE"
echo "   URL: https://business.google.com"
echo "   Actions:"
echo "   - Update business information"
echo "   - Add services and specializations"
echo "   - Update appointment booking: $APPOINTMENT_LINK"
echo "   - Add teleconsult option: $TELECONSULT_LINK"
echo "   - Post regular updates about services"
echo ""

echo "📊 Verification Steps:"
echo "====================="
echo "1. Search 'Dr. Sayuj Krishnan neurosurgeon Hyderabad' on Google"
echo "2. Check NAP consistency across all results"
echo "3. Verify appointment links are working"
echo "4. Test UTM tracking in Google Analytics"
echo "5. Monitor citation directory rankings"
echo ""

echo "🎯 Expected Results:"
echo "==================="
echo "- Improved local search visibility"
echo "- Higher click-through rates from citations"
echo "- Better NAP consistency score"
echo "- Increased appointment bookings via UTM tracking"
echo ""

echo "📅 Next Steps:"
echo "=============="
echo "1. Update each directory systematically"
echo "2. Take screenshots of before/after changes"
echo "3. Monitor Google Analytics for UTM traffic"
echo "4. Set up Google Alerts for business mentions"
echo "5. Schedule monthly citation audits"
echo ""

echo "🔗 Useful Tools:"
echo "==============="
echo "- Google My Business: https://business.google.com"
echo "- Citation Tracker: https://www.brightlocal.com/local-citation-tracker/"
echo "- NAP Checker: https://www.whitespark.ca/nap-checker"
echo "- UTM Builder: https://ga-dev-tools.google/campaign-url-builder/"
echo ""

echo "✅ Ready to update citations! Start with Google Business Profile first."
